---

en-GB:
    ui_unit_verbs_build: Build
    ui_unit_verbs_mine: Mine
    ui_unit_verbs_dismiss: Dismiss
    ui_unit_verbs_repair: Repair
    ui_unit_verbs_tech_up: Advance Tech
    ui_unit_verbs_pick_up: Pick Up
    structure_name_gold: Gold
    structure_name_gold_camp: Mining Camp
    equipment_name_short_sword: Short Sword
    unit_description_gold: Vaulable resources. Can be mined by constructing a mining camp on top of it and staff it with villagers
    unit_description_gold_camp: Mining camp for gold. Garrison with villagers to start mining 50 gold per villager per turn
    unit_description_short_sword: Plain short sword. Increases minimal damage dealt by 3%
...