---

en-GB:
    ui_unit_verbs_build: Build
    ui_unit_verbs_mine: Mine
    ui_unit_verbs_dismiss: Dismiss
    ui_unit_verbs_repair: Repair
    ui_unit_verbs_tech_up: Advance Tech
    ui_unit_verbs_pick_up: Pick Up
    ui_unit_verbs_drink_h_pot: Drink H-Potion
    ui_unit_verbs_drink_g_pot: Drink G-Potion
    ui_unit_verbs_dimensional_door: Recall
    ui_unit_verbs_buy_artifacts: Buy Artifacts
    groove_name_dimensional_door: Dimensional Door
    groove_description_dimensional_door: A relic from the anicent. Allows the wielder to teleport to a tile beside HQ. 5 turn cooldown
    groove_name_indicate_population: Population
    groove_description_indicate_population: The Current Population
    structure_name_gold: Gold
    structure_name_gold_camp: Mining Camp
    structure_name_shop: Shop
    equipment_name_short_sword: Short Sword
    equipment_name_rare_sword: Sword of Death
    equipment_name_axe: Battle Axe
    equipment_name_dagger: Hidden Dagger
    equipment_name_shield: Round Shield
    equipment_name_rare_shield: Shield of Life
    equipment_name_armor: Plate Armor
    equipment_name_helmet: Great Helm
    equipment_name_health_pot: Health Potion
    equipment_name_groove_pot: Groove Potion
    equipment_name_bow: Hunting Bow
    equipment_name_dimensional_door: Dimensional Door
    unit_description_gold: Vaulable resources. Can be mined by constructing a mining camp on top of it and staff it with villagers
    unit_description_gold_camp: Mining camp for gold. Garrison with villagers to start mining 50 gold per villager per turn
    unit_description_shop: Shop selling 5 random artifacts. restocks every 5 turns.
    unit_description_short_sword: Well forged short sword. Increases the wielder's overall damage by 2%
    unit_description_rare_sword: A sword of unknown origin. Increases the wielder's overall damage by 2%, min and max damage by 3%
    unit_description_axe: A double bladed battle axe. Increases the wielder's maximal damage by 3%
    unit_description_dagger: Small and nimble dagger. Increases the wielder's minimal damage by 3%
    unit_description_shield: Small shield made of pure metal. Lower incoming damage by 2%
    unit_description_rare_shield: Shield inbused with essense of Life. Lower incoming damage by 2, min and max damage by 3%
    unit_description_armor: Full body plated armor. Lower incoming minimal damage by 3%
    unit_description_helmet: Great helm covering the entire head. Lower incoming maximal damage by 3%
    unit_description_health_pot: Filled with weird red goo, increases hp by 25 (points, not percentage)
    unit_description_groove_pot: Filled with weird blue goo, increases groove by 25 (points, not percentage)
    unit_description_bow: A bow used by skilled hunter. Allows the wielder to use ranged attack at half the damage
    unit_description_dimensional_door: A relic from the anicent. Allows the wielder to teleport to a tile beside HQ. 5 turn cooldown
...