---

en-GB:
    ui_unit_verbs_build: Build
    ui_unit_verbs_mine: Mine
    ui_unit_verbs_dismiss: Dismiss
    ui_unit_verbs_repair: Repair
    ui_unit_verbs_tech_up: Advance Tech
    ui_unit_verbs_pick_up: Pick Up
    structure_name_gold: Gold
    structure_name_gold_camp: Mining Camp
    equipment_name_short_sword: Short Sword
    equipment_name_axe: Battle Axe
    equipment_name_dagger: Hidden Dagger
    unit_description_gold: Vaulable resources. Can be mined by constructing a mining camp on top of it and staff it with villagers
    unit_description_gold_camp: Mining camp for gold. Garrison with villagers to start mining 50 gold per villager per turn
    unit_description_short_sword: Well forged short sword. Increases the wielder's overall damage by 2%
    unit_description_axe: A double bladed battle axe. Increases the wielder's maximal damage by 3%
    unit_description_dagger: Small and nimble dagger. Increases the wielder's minimal damage by 3%
...