---

modifyingUnitClasses:
  - id: barracks
    replace:
        income: 0
        regeneration: 0
        canBeCaptured: true
        canReinforce: false
        cost: 300
        isNeutraliseable: false
        verbs:
            - recruit_two
            - wait
        tags:
            - structure
            - salvageable

...