---

modifyingUnitClasses:
  - id: barracks
    replace:
        income: 0
        regeneration: 0
        canBeCaptured: false
        canReinforce: false
        cost: 200
        isNeutraliseable: false
        verbs:
            - recruit_two

...