---

unitClasses:
  - id: church
    name: structure_name_church
    aiPriority: 4.0
    moveRange: 0
    isStructure: true
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: true
    isNeutraliseable: false
    damageMultiplier: 1
    battleUnitCount: 1
    hostileNeutral: false
    garrisonUnit: ""
    movement: land_building
    recruitTags: [type.ground.healer]
    income: 0
    loadCapacity: 1
    cost: 250
    grooveId: indication_progress
    tags:
      - structure
      - salvageable
    verbs:
      - recruit_two
      - recruit_two_phase_two
      - cancel_recruit
      
units:
  - class: church
    faction: neutral
    name: structure_name_church
    mapAnimation: [units/structures/church/map_church]
    smallPortrait: portraits/small/portrait_structure_small.png
    mediumPortrait: units/structures/church/portrait_church_medium.png
    grabPos: [12, 5]
    hasBattleScreen: false
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie
    structureImage:
      spriteSheet: backgrounds/city/city_background_full
      farBackground: city_background_full_background_2
      nearBackground: city_background_full_background_1
      foreground: city_background_full_foreground
      keeperPosition: [78, 95]
      leftBannerOffset: [-6, 2]
      rightBannerOffset: [0, 2]

...