---

modifyingUnitClasses:
  - id: city
    replace:
        income: 0
        regeneration: 0
        canBeCaptured: false
        canReinforce: true
        cost: 100
        isNeutraliseable: false
...