---

modifyingUnitClasses:
  - id: hq
    replace:
        income: 0
        regeneration: 0
        canBeCaptured: false
        canReinforce: false
        cost: 750
        verbs:
          - recruit_two
          - tech_up
        recruitTags: [type.ground.villager]
        loadCapacity: 2

...