---

modifyingUnitClasses:
  - id: port
    replace:
        income: 0
        regeneration: 0
        canBeCaptured: false
        canReinforce: false
        cost: 300
        isNeutraliseable: false

...