---

modifyingUnitClasses:
  - id: port
    replace:
        income: 0
        regeneration: 0
        canBeCaptured: true
        canReinforce: false
        cost: 300
        isNeutraliseable: false
        loadCapacity: 1
        verbs:
            - recruit_two
            - recruit_two_phase_two
            - cancel_recruit
        tags:
            - structure
            - salvageable
        grooveId: indication_progress
...