---

modifyingUnitClasses:
  - id: tower
    replace:
        income: 0
        regeneration: 0
        canBeCaptured: false
        canReinforce: false
        cost: 400
        isNeutraliseable: false
        verbs:
            - recruit_two
            - wait

...