---

unitClasses:
  - id: armor
    name: equipment_name_armor
    aiPriority: 2.0
    moveRange: 0
    isStructure: false
    classIconSpritesheet: ui_AgeOfWarGrooveMod
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: false
    isNeutraliseable: false
    damageMultiplier: 1
    hostileNeutral: true
    garrisonUnit: ""
    movement: walking
    income: 0
    cost: 250
    tags:
      - equipment

units:
  - class: armor
    faction: neutral
    name: equipment_name_armor
    mapAnimation: units/equipments/armor/map_armor
    smallPortrait: units/equipments/armor/portrait_armor_small.png
    mediumPortrait: units/equipments/armor/portrait_armor_medium.png
    battleAnimation: units/equipments/armor/battle_armor
    grabPos: [12, 5]
    hasBattleScreen: false
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie

...