---

unitClasses:
  - id: axe
    name: equipment_name_axe
    aiPriority: 2.0
    moveRange: 0
    isStructure: false
    classIconSpritesheet: ui_AgeOfWarGrooveMod
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: false
    isNeutraliseable: false
    damageMultiplier: 1
    hostileNeutral: true
    garrisonUnit: ""
    movement: walking
    income: 0
    cost: 250
    tags:
      - equipment

units:
  - class: axe
    faction: neutral
    name: equipment_name_axe
    mapAnimation: units/equipments/axe/map_axe
    smallPortrait: units/equipments/axe/portrait_axe_small.png
    mediumPortrait: units/equipments/axe/portrait_axe_medium.png
    battleAnimation: units/equipments/axe/battle_axe
    grabPos: [12, 5]
    hasBattleScreen: false
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie

...