---

unitClasses:
  - id: helmet
    name: equipment_name_helmet
    aiPriority: 2.0
    moveRange: 0
    isStructure: false
    classIconSpritesheet: ui_AgeOfWarGrooveMod
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: false
    isNeutraliseable: false
    damageMultiplier: 1
    hostileNeutral: true
    garrisonUnit: ""
    movement: walking
    income: 0
    cost: 250
    tags:
      - equipment

units:
  - class: helmet
    faction: neutral
    name: equipment_name_helmet
    mapAnimation: units/equipments/helmet/map_helmet
    smallPortrait: units/equipments/helmet/portrait_helmet_small.png
    mediumPortrait: units/equipments/helmet/portrait_helmet_medium.png
    battleAnimation: units/equipments/helmet/battle_helmet
    grabPos: [12, 5]
    hasBattleScreen: false
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie

...