---

unitClasses:
  - id: rare_sword
    name: equipment_name_rare_sword
    aiPriority: 2.0
    moveRange: 0
    isStructure: false
    classIconSpritesheet: ui_AgeOfWarGrooveMod
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: false
    isNeutraliseable: false
    damageMultiplier: 1
    hostileNeutral: true
    garrisonUnit: ""
    movement: walking
    income: 0
    cost: 750
    tags:
      - equipment

units:
  - class: rare_sword
    faction: neutral
    name: equipment_name_rare_sword
    mapAnimation: units/equipments/rare_sword/map_rare_sword
    smallPortrait: units/equipments/rare_sword/portrait_rare_sword_small.png
    mediumPortrait: units/equipments/rare_sword/portrait_rare_sword_medium.png
    battleAnimation: units/equipments/rare_sword/battle_rare_sword
    grabPos: [12, 5]
    hasBattleScreen: false
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie

...