---

unitClasses:
  - id: short_sword
    name: equipment_name_short_sword
    aiPriority: 2.0
    moveRange: 0
    isStructure: false
    classIconSpritesheet: ui_AgeOfWarGrooveMod
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: false
    isNeutraliseable: false
    damageMultiplier: 1
    hostileNeutral: true
    garrisonUnit: ""
    movement: walking
    income: 0
    cost: 350
    tags:
      - equipment

units:
  - class: short_sword
    faction: neutral
    name: equipment_name_short_sword
    mapAnimation: units/equipments/short_sword/map_short_sword
    smallPortrait: units/equipments/short_sword/portrait_short_sword_small.png
    mediumPortrait: units/equipments/short_sword/portrait_short_sword_medium.png
    battleAnimation: units/equipments/short_sword/battle_short_sword
    grabPos: [12, 5]
    hasBattleScreen: false
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie

...