---

unitClasses:
  - id: short_sword
    name: equipment_name_short_sword
    aiPriority: 2.0
    moveRange: 0
    isStructure: false
    canReinforce: false
    canBeReinforced: false
    canBeCaptured: false
    isNeutraliseable: true
    damageMultiplier: 10
    hostileNeutral: true
    garrisonUnit: ""
    movement: hovering
    income: 0
    cost: 250
    tags:
      - equipment
      
units:
  - class: short_sword
    faction: neutral
    name: equipment_name_short_sword
    mapAnimation: [units/equipments/short_sword]
    smallPortrait: units/equipments/short_sword_small.png
    mediumPortrait: units/equipments/short_sword_medium.png
    grabPos: [12, 5]
    hasBattleScreen: false
    sounds:
      hit: hitWood
      hitMap: hitStone
      death: gateDie
    structureImage:
      spriteSheet: backgrounds/city/city_background_full
      farBackground: city_background_full_background_2
      nearBackground: city_background_full_background_1
      foreground: city_background_full_foreground
      keeperPosition: [78, 95]
      leftBannerOffset: [-6, 2]
      rightBannerOffset: [0, 2]

...