---
codex:

- id: rules_income
  category: rules
  name: codex_rules_income
  icon:
    image: ui/codex/icons/icon_rules_question.png
  pages:
  - pageType: page
    layoutType: animation
    animation: ui/codex/content/rules_income_2
    title: codex_rules_income_title
    text: codex_rules_income_text

- id: rules_gold_mines
  category: rules
  name: codex_rules_gold_mines
  icon:
    image: ui/codex/icons/icon_rules_question.png
  pages:
  - pageType: page
    layoutType: animation
    animation: ui/codex/content/rules_mine
    title: codex_rules_gold_mines_title
    text: codex_rules_gold_mines_text

- id: rules_tech
  category: rules
  name: codex_rules_tech
  icon:
    image: ui/codex/icons/icon_rules_question.png
  pages:
  - pageType: page
    layoutType: animation
    animation: ui/codex/content/rules_tech
    title: codex_rules_tech_title
    text: codex_rules_tech_text

- id: rules_building
  category: rules
  name: codex_rules_building
  icon:
    image: ui/codex/icons/icon_rules_question.png
  pages:
  - pageType: page
    layoutType: animation
    animation: ui/codex/content/rules_build
    title: codex_rules_building_title
    text: codex_rules_building_text

- id: rules_repairing
  category: rules
  name: codex_rules_repair
  icon:
    image: ui/codex/icons/icon_rules_question.png
  pages:
  - pageType: page
    layoutType: animation
    animation: ui/codex/content/rules_repair
    title: codex_rules_repair_title
    text: codex_rules_repair_text

- id: rules_pop_cap
  category: rules
  name: codex_rules_pop_cap
  icon:
    image: ui/codex/icons/icon_rules_question.png
  pages:
  - pageType: page
    layoutType: animation
    animation: ui/codex/content/rules_pop_cap
    title: codex_rules_pop_cap_title
    text: codex_rules_pop_cap_text

- id: rules_artifacts
  category: rules
  name: codex_rules_artifacts
  icon:
    image: ui/codex/icons/icon_rules_question.png
  pages:
  - pageType: page
    layoutType: animation
    animation: ui/codex/content/rules_artifact
    title: codex_rules_artifacts_title
    text: codex_rules_artifacts_text

- id: rules_shop
  category: rules
  name: codex_rules_shop
  icon:
    image: ui/codex/icons/icon_rules_question.png
  pages:
  - pageType: page
    layoutType: animation
    animation: ui/codex/content/rules_shop
    title: codex_rules_shop_title
    text: codex_rules_shop_text


...
