---

verbs:
  - id: build
    icon: ui/icons/unit_action_icon_build.png
    name: ui_unit_verbs_build
    targetColour: target
    targetOutlineColour: target_outline
    preExecute: true
    scriptName: verbs/build
    aiUses: true
  - id: recruit_two
    icon: ui/icons/unit_action_icon_recruit.png
    name: ui_unit_verbs_recruit
    targetColour: target
    targetOutlineColour: target_outline
    preExecute: true
    scriptName: verbs/recruit_two
    aiUses: true
  - id: mine
    icon: ui/icons/unit_action_icon_mine.png
    name: ui_unit_verbs_mine
    targetColour: target
    targetOutlineColour: target_outline
    scriptName: verbs/mine
    targetted: true
    directTarget: true
    aiUses: true
  - id: spell_heal
    icon: ui/icons/grooves/unit_action_icon_heal2.png
    name: ui_unit_verbs_spell_heal
    targetColour: target
    targetOutlineColour: target_outline
    splashOutlineColour: heal_outline
    scriptName: verbs/spell_heal
    targetted: true
    splashRadius: 1
    hasResourceCost: false
  - id: recruit
    icon: ui/icons/unit_action_icon_recruit.png
    name: ui_unit_verbs_recruit
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
    scriptName: verbs/recruit
  - id: repair
    preExecute: false
    icon: ui/icons/unit_action_icon_build.png
    name: ui_unit_verbs_repair
    scriptName: verbs/repair
    hasResourceCost: false
    targetted: true
    directTarget: true
    targetColour: target
    targetOutlineColour: target_outline
  - id: tech_up
    icon: ui/icons/unit_action_icon_tech_up.png
    name: ui_unit_verbs_tech_up
    scriptName: verbs/tech_up
    targetted: false
    hasResourceCost: true
  - id: pick_up
    icon: ui/icons/unit_action_icon_load.png
    name: ui_unit_verbs_pick_up
    targetColour: target
    targetOutlineColour: target_outline
    targetted: true
    directTarget: true
    scriptName: verbs/pick_up
  - id: unload_two
    icon: ui/icons/unit_action_icon_unload.png
    name: ui_unit_verbs_unload
    targetColour: target
    targetOutlineColour: target_outline
    preExecute: true
    scriptName: verbs/unload_two
    aiUses: true

...