---

verbs:
  - id: build
    icon: ui/icons/unit_action_icon_build.png
    name: ui_unit_verbs_build
    targetColour: target
    targetOutlineColour: target_outline
    preExecute: true
    scriptName: verbs/build
    aiUses: true
  - id: mine
    icon: ui/icons/unit_action_icon_mine.png
    name: ui_unit_verbs_mine
    targetColour: target
    targetOutlineColour: target_outline
    scriptName: verbs/mine
    targetted: true
    directTarget: true
    aiUses: true
  - id: spell_heal
    icon: ui/icons/grooves/unit_action_icon_heal2.png
    name: ui_unit_verbs_spell_heal
    targetColour: target
    targetOutlineColour: target_outline
    splashOutlineColour: heal_outline
    scriptName: verbs/spell_heal
    targetted: true
    splashRadius: 1
    hasResourceCost: false
  - id: repair
    preExecute: false
    icon: ui/icons/unit_action_icon_build.png
    name: ui_unit_verbs_repair
    scriptName: verbs/repair
    hasResourceCost: false
    targetted: true
    directTarget: true
    targetColour: target
    targetOutlineColour: target_outline

...